### ISSUE TITLE
Set-Up Failure (Auth Failure)

### ISSUE THREAD

**Issue by SpecialK1417** [simbaja/ha_gehome#15]
When performing component initialization I get the error pasted below. I have also tried the ge_kitchen component from ajmarks repository which does not have the authentication error. Same login info of course.
I've tried manual installation and HACS with no success. Anything ideas?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:155
Integration: GE Home (documentation)
First occurred: 4:12:48 PM (1 occurrences)
Last logged: 4:12:48 PM

Error setting up entry GE Home (******@gmail.com) for ge_home

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 153, in async_setup
    await self.async_start_client()
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_start_client
    await self.async_begin_session()
  File "/config/custom_components/ge_home/update_coordinator.py", line 182, in async_begin_session
    await self.client.async_get_credentials(session)
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/base_client.py", line 179, in async_get_credentials
    await self.async_do_full_login_flow()
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/base_client.py", line 183, in async_do_full_login_flow
    self.credentials = await self._async_do_full_login_flow()
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/websocket_client.py", line 61, in _async_do_full_login_flow
    await self._async_get_oauth2_token()
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/base_client.py", line 206, in _async_get_oauth2_token
    oauth_token = await async_get_oauth2_token(self._session, self.account_username, self.account_password)
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/async_login_flows.py", line 67, in async_get_oauth2_token
    raise GeAuthFailedError(await resp.text())
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: {
 "error": "invalid_grant",
 "error_description": "Invalid Authorization Code"
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 155, in async_setup
    raise HaAuthError('Authentication failure')
custom_components.ge_home.exceptions.HaAuthError: Authentication failure

**Comment by simbaja** [comment]
Any chance you can run the latest version of the underlying library (simbaja\gehome) and see if you still get an error?  You'll need to create a secrets.py file with your credentials, but it should be possible to step through the logic to see what's going on there.  I haven't seen this issue reported elsewhere, wondering if there's some sort of encoding issue or something.  Most of the auth code is untouched from Andrew's version, just reorganized, so surprised that it's not exhibiting issues.

**Comment by simbaja** [comment]
Hopefully this has been resolved, please feel free to reopen if not.
