### ISSUE TITLE
DishDrawer fails to be recognised in HA

### ISSUE THREAD

**Issue by kclif9** [simbaja/ha_gehome#166]
Our DishDrawer is not recognised in HA. Seen the below error message shown in HA logs.

Logger: homeassistant
Source: custom_components/ge_home/devices/dual_dishwasher.py:22
Integration: GE Home ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 1:40:20 PM (1 occurrences)
Last logged: 1:40:20 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 303, in on_device_initial_update
    self.maybe_add_appliance_api(appliance)
  File "/config/custom_components/ge_home/update_coordinator.py", line 135, in maybe_add_appliance_api
    api.build_entities_list()
  File "/config/custom_components/ge_home/devices/base.py", line 135, in build_entities_list
    e for e in self.get_all_entities()
  File "/config/custom_components/ge_home/devices/dual_dishwasher.py", line 22, in get_all_entities
    GeErdSensor(self, ErdCode.DISHWASHER_RINSE_AGENT, erd_override="lower_rinse_agent", icon_override="mdi:shimmer"),
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: DISHWASHER_RINSE_AGENT

**Comment by simbaja** [comment]
Fixed in #161, you can either pull manually from the "dev" branch or wait for the next release.
