### ISSUE TITLE
Washer and Dryer showing as Unavailable after several hours of working

### ISSUE THREAD

**Issue by dmcnaughton** [simbaja/ha_gehome#17]
Woke up this morning to seeing the entity statuses for both my washer and dryer show as unavailable. The only errors logged in HA are below:

Logger: aiohttp.server
Source: /usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py:393
First occurred: 8:16:54 AM (52 occurrences)
Last logged: 8:21:39 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by dmcnaughton** [comment]
Additional logs:



Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:165
Integration: GE Home (documentation)
First occurred: 8:17:26 AM (1 occurrences)
Last logged: 8:17:26 AM
Error setting up entry GE Home (danieljmcnaughton@gmail.com) for ge_home

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 163, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 163, in async_setup
    await self.initialization_future
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 165, in async_setup
    raise HaCannotConnect('Initialization timed out')
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

**Comment by simbaja** [comment]
Interesting that it was working, but now is not.  Any chance you can run a debug session in the sdk itself just to see if there's some more debug information available?  The sdk can be found at simbaja\gehome.  You may need to increase the run time of the websocket example to see if there's something that triggers this.

Also, we're revamping the laundry stuff as well, so some of the upcoming fixes might resolve this issue.

**Comment by simbaja** [comment]
Marking this as closed, feel free to re-open if you run into the issue again.
