### ISSUE TITLE
F&P dual dishwasher, fails to init with ValueError in UserCycleSetting

### ISSUE THREAD

**Issue by fivesixzero** [simbaja/ha_gehome#172]
I'm setting up the integration for the first time and ran into an issue with a new F&P dual-drawer dishwasher, model `DD24DTX6PX1`  (`DD613US` in app).

Installing the integration via HACS and logging in went well but after setup no entitites showed up. Here's what showed up in the logs.

```py
2023-06-10 11:47:05.323 ERROR (MainThread) [gehomesdk.erd.converters.dishwasher.erd_user_setting_converter] Could not construct user setting, using default.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gehomesdk/erd/converters/dishwasher/erd_user_setting_converter.py", line 28, in erd_decode
    cycle_mode = UserCycleSetting((i & 14) >> 1),   #missing brackets added by Nick
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 7 is not a valid UserCycleSetting
2023-06-10 11:47:05.323 ERROR (MainThread) [gehomesdk.erd.converters.dishwasher.erd_user_setting_converter] Could not construct user setting, using default.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gehomesdk/erd/converters/dishwasher/erd_user_setting_converter.py", line 28, in erd_decode
    cycle_mode = UserCycleSetting((i & 14) >> 1),   #missing brackets added by Nick
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 7 is not a valid UserCycleSetting
2023-06-10 11:47:05.324 ERROR (MainThread) [gehomesdk.erd.converters.dishwasher.erd_user_setting_converter] Could not construct user setting, using default.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gehomesdk/erd/converters/dishwasher/erd_user_setting_converter.py", line 28, in erd_decode
    cycle_mode = UserCycleSetting((i & 14) >> 1),   #missing brackets added by Nick
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 7 is not a valid UserCycleSetting
2023-06-10 11:47:05.325 ERROR (MainThread) [gehomesdk.erd.converters.dishwasher.erd_user_setting_converter] Could not construct user setting, using default.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gehomesdk/erd/converters/dishwasher/erd_user_setting_converter.py", line 28, in erd_decode
    cycle_mode = UserCycleSetting((i & 14) >> 1),   #missing brackets added by Nick
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 7 is not a valid UserCycleSetting
2023-06-10 11:47:05.326 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 303, in on_device_initial_update
    self.maybe_add_appliance_api(appliance)
  File "/config/custom_components/ge_home/update_coordinator.py", line 135, in maybe_add_appliance_api
    api.build_entities_list()
  File "/config/custom_components/ge_home/devices/base.py", line 135, in build_entities_list
    e for e in self.get_all_entities()
  File "/config/custom_components/ge_home/devices/dual_dishwasher.py", line 22, in get_all_entities
    GeErdSensor(self, ErdCode.DISHWASHER_RINSE_AGENT, erd_override="lower_rinse_agent", icon_override="mdi:shimmer"),
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: DISHWASHER_RINSE_AGENT
```

I wanted to be helpful and see if I could get a PR submitted here or in the `gehome` repo alongside the issue but I haven't played with this API before and it looks like the API docs are behind a registration wall that I don't have the time to jump over this weekend.

The first issue, the `ValueError`, looks like a simple missing state ID in the enum. The appliance itself is currently off, so I'm not sure exactly what the `UserCycleSetting` ID of `7` actually refers to, although it may be in the API docs.

The second issue, the `AttributeError`, looks like a missing value in the `ErdCode` enum, which looks like it's already been fixed in #161 according to issue #166. So that's good! :)

Let me know if any more information is required, I'll be happy to help.

**Comment by simbaja** [comment]
I haven't created a formal release, but the latest version on the dev branch should have something to patch this.  I just gave it the name "FP_UNKNOWN" for now since we don't know what it is.  If you figure it out, let me know.

**Comment by fivesixzero** [comment]
Cool, just saw [the commit](https://github.com/simbaja/gehome/commit/62edb2bb46043dab99124befbbd4b6ea89b79aed) in the lib repo. Thanks! Looks like everything should be working in my HA instance once a new release is pushed that includes #161.

As far as what the `UserCycleSetting` of `7` is, I'm still scratching my head. It was freshly installed and was idle but may have recently completed its first cycle, or possibly a self-cleaning cycle. Was kinda hoping the vendor API docs would have something but couldn't just casually browse without signing up. 🤷

**Comment by simbaja** [comment]
New release created, let me know if I need to reopen this if something goes amiss.

**Comment by fivesixzero** [comment]
Finaly had time to test this out, things worked as expected during setup this time. Thanks!
