### ISSUE TITLE
GE Café Specialty Drip Coffee Maker no longer brews coffee through integration 

### ISSUE THREAD

**Issue by papirov** [simbaja/ha_gehome#186]
Hello!
Thank you for the wonderful work you're doing on the integration.  My integration stopped being able to make coffee some time ago (I came back from a long vacation) and now, the "Start Brewing" button no longer does anything, even though the integration picks up all of the settings from the coffee maker properly.  Integration is on the v0.6.7 version

Any advice?

**Logs that are relevant (with debugging enabled for the device) after the "Start Brewing" button was pressed**

Logger: homeassistant.helpers.service
Source: helpers/service.py:833
First occurred: 8:13:45 AM (5 occurrences)
Last logged: 8:47:44 AM

Referenced entities button.d828c96ed9d3_ccm_brew_settings are missing or not currently available
Referenced entities button.d828c96ed9d3_ccm_cancel_brewing are missing or not currently available

Logger: homeassistant
Source: helpers/entity.py:723
First occurred: 12:14:26 AM (1756 occurrences)
Last logged: 8:47:41 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 269, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 723, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity None=off>

![image](https://github.com/simbaja/ha_gehome/assets/2907836/be3db0b1-46db-4f97-877c-c645428b98a9)
[Coffee Maker](https://www.amazon.com/gp/product/B0964C3BT4/)

**Comment by brylee123** [comment]
I believe I have the same problem. Sometimes the cards show that it is connected while in reality, it is not.

![image](https://github.com/simbaja/ha_gehome/assets/22011502/2a554a45-02d1-49fa-af7e-0eb72eeeac42)

I am having trouble pulling up full logs but this is what I can filter out:

```
=========================================================
Logger: gehomesdk.clients.base_client
Source: runner.py:179
First occurred: August 16, 2023 at 11:34:12 PM (2122 occurrences)
Last logged: 9:57:09 AM

Error refreshing authentication: Could not refresh OAuth token
Unhandled exception on first connect attempt: , disconnecting
=========================================================
Logger: gehomesdk.clients.websocket_client
Source: runner.py:179
First occurred: 12:16:12 AM (355 occurrences)
Last logged: 9:56:27 AM

Unknown error reading socket
=========================================================
Logger: gehomesdk.clients.websocket_client
Source: /usr/local/lib/python3.11/site-packages/gehomesdk/clients/websocket_client.py:121
First occurred: 8:10:22 AM (2 occurrences)
Last logged: 8:10:22 AM

Could not process request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/websocket_client.py", line 119, in _async_run_client
    await self._process_message(message)
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/websocket_client.py", line 277, in _process_message
    raise GeRequestError(message, message_dict.get("code"), message_dict.get("reason"))
gehomesdk.exception.ge_request_error.GeRequestError: There was an error while processing a message: Code=None, Reason=Internal server error, Message={"kind":"websocket#subscribe","success":false,"reason":"Internal server error"}
```

**Comment by Treygec** [comment]
Just coming to this repository today, was able to get it connected and pull in my oven, but my Cafe Specialty Grind and Brew didn't get pulled in at all. Any chance you got this working or has this device stopped working entirely?

**Comment by simbaja** [comment]
Any chance you guys can try the latest pre-release (see #423) and see if it improves things?  The errors that you are reporting seem to indicate connection issues.  I've refactored the internal logic to hopefully make more stable.
