### ISSUE TITLE
Error stopping entities being created now

### ISSUE THREAD

**Issue by Ovaro** [simbaja/ha_gehome#191]
Hi- this integration was previously working- however now I am getting:

----
Logger: homeassistant
Source: custom_components/ge_home/devices/dual_dishwasher.py:22
Integration: GE Home (SmartHQ) ([documentation](https://github.com/simbaja/ha_gehome))
First occurred: 30 August 2023 at 20:23:56 (37 occurrences)
Last logged: 16:57:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 303, in on_device_initial_update
    self.maybe_add_appliance_api(appliance)
  File "/config/custom_components/ge_home/update_coordinator.py", line 135, in maybe_add_appliance_api
    api.build_entities_list()
  File "/config/custom_components/ge_home/devices/base.py", line 135, in build_entities_list
    e for e in self.get_all_entities()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ge_home/devices/dual_dishwasher.py", line 22, in get_all_entities
    GeErdSensor(self, ErdCode.DISHWASHER_RINSE_AGENT, erd_override="lower_rinse_agent", icon_override="mdi:shimmer"),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: DISHWASHER_RINSE_AGENT

**Comment by simbaja** [comment]
Hmm, seems like you might be running an earlier version (that code doesn't exist in the latest couple versions).  Please let me know if doing so doesn't fix it and I can reopen.
