### ISSUE TITLE
Fisher and Paykel Drawer Dishwasher - Error on User Cycle Setting  

### ISSUE THREAD

**Issue by yestrdave** [simbaja/ha_gehome#214]
Core
2023.12.1
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231208.2

2023-12-13 08:53:27.290 ERROR (MainThread) [gehomesdk.erd.converters.dishwasher.erd_user_setting_converter] Could not construct user setting, using default.
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/gehomesdk/erd/converters/dishwasher/erd_user_setting_converter.py", line 28, in erd_decode
cycle_mode = UserCycleSetting((i & 14) >> 1), #missing brackets added by Nick
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
return cls.__new__(cls, value)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
raise ve_exc
ValueError: 6 is not a valid UserCycleSetting

**Comment by simbaja** [comment]
Any idea what the cycle setting value of 6 represents?

**Comment by yestrdave** [comment]
Sorry I have been traveling for work. I do not have any idea.  Is there anything I can do to help?

**Comment by simbaja** [comment]
What is the cycle set to on your dishwasher?

**Comment by yestrdave** [comment]
![image](https://github.com/simbaja/ha_gehome/assets/93943061/497119d9-4a7c-4392-bc3d-8461238a8d2e)

At the moment medium.  I just glanced at logs. Doesn't look like I have the error today.  Do you think the different settings are cause?
