### ISSUE TITLE
Error Message For GE Home.  Task exception was never retrieved.  Error every 30 seconds.

### ISSUE THREAD

**Issue by laplacacm** [simbaja/ha_gehome#215]
I am receiving the following error message.  I get three in a row exactly every 30 seconds.

Home Assistant OS -  2023.12.3
Most up-to-date GE Home integration as well. 

2023-12-20 18:36:29.185 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 280, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for

**Comment by simbaja** [comment]
Please use the pre-release version, it should resolve this error.
