### ISSUE TITLE
Error adding entities for domain climate with platform ge_home

### ISSUE THREAD

**Issue by bdog720** [simbaja/ha_gehome#228]
Noticed this after the in the last day. Not sure if it was the 0.6.9 update or something else

I've attempted the troubleshooting steps and there's no change (including a deleting the component all together and rebooting HA and starting again

I can see other entities for my AC and I can turn it on and off but it's not recognised as a climate device

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Climate (documentation, issues)

Error adding entities for domain climate with platform ge_home
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 329, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1474, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'ClimateEntityFeature' and 'WaterHeaterEntityFeature'
```

Logger: homeassistant
Source: components/climate/__init__.py:329

Error doing job: Task exception was never retrieved
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 329, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1474, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'ClimateEntityFeature' and 'WaterHeaterEntityFeature'
```

**Comment by simbaja** [comment]
Looks like one of the changes from 0.6.9 to fix deprecated constants.  I'll try to get a new version out that fixes this.

**Comment by bdog720** [comment]
Awesome! Thanks for responding so quickly

**Comment by simbaja** [comment]
Can you try the pre-release 0.6.10-dev0 and see if it resolves this issue?

**Comment by bdog720** [comment]
Yes that solved the issue!
