### ISSUE TITLE
Exceeded limit of 600 requests per minute per appId per userId

### ISSUE THREAD

**Issue by fromonesource** [simbaja/ha_gehome#236]
```
[31m2024-03-02 14:19:57.363 ERROR (MainThread) [gehomesdk.clients.websocket_client] Could not process request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 119, in _async_run_client
    await self._process_message(message)
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 277, in _process_message
    raise GeRequestError(message, message_dict.get("code"), message_dict.get("reason"))
gehomesdk.exception.ge_request_error.GeRequestError: There was an error while processing a message: Code=429, Reason=None, Message={"kind":"websocket#api","id":"REDACTED","request":{"host":"api.brillion.geappliances.com","method":"GET","path":"/v1/appliance/REDACTED/erd"},"success":true,"code":429,"body":{"kind":"error","resource":"/v1/appliance/REDACTED/erd","code":429,"message":"The server is refusing to service the request because the user has sent too many requests in a given amount of time (\"rate limiting\")","reason":"Exceeded limit of 600 requests per minute per appId per userId."}}[0m
```

I have thousands of these spamming my log aggregator. What is causing this? It seems that gehome is not doing a backoff retry as I can see about 10 requests per second erroring with 429 response. I have noticed some correlation with my hass system completely locking up after hours of retried requests and 429 responses which requires me to restart hass completely.

**Comment by simbaja** [comment]
What version of the component are you using?  If it's the latest, can you provide any other information?
