### ISSUE TITLE
Blocking call to load_default_certs

### ISSUE THREAD

**Issue by rlippmann** [simbaja/ha_gehome#297]
From the logs:

2024-10-27 11:03:54.249 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x731c38ab2150>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) in /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
**File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client
await self._async_run_client()
File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 110, in _async_run_client
async with websockets.connect(self.endpoint, compression=None) as socket:**
File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 635, in __aenter__
return await self
File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
_transport, protocol = await self._create_connection()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1173, in _create_connection_transport
transport = self._make_ssl_transport(
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 83, in _make_ssl_transport
ssl_protocol = sslproto.SSLProtocol(
File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 295, in __init__
sslcontext = _create_transport_context(
File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 55, in _create_transport_context
sslcontext = ssl.create_default_context()
File "/usr/local/lib/python3.12/ssl.py", line 713, in create_default_context
context.load_default_certs(purpose)

**Comment by Waank1** [comment]
I am running:
Core - 2024.10.4
Supervisor - 2024.10.3
Operating System - 13.2
Frontend - 20241002.4

I have also been getting this same error for quite some time, sorry but I can't remember exactly when it started.  Here is what the logs say:

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 16:13:59 (1 occurrences)
Last logged: 16:13:59

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fd8a18367d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) in /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client await self._async_run_client() File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 110, in _async_run_client async with websockets.connect(self.endpoint, compression=None) as socket: File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 635, in __aenter__ return await self File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__ _transport, protocol = await self._create_connection() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1173, in _create_connection_transport transport = self._make_ssl_transport( File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 83, in _make_ssl_transport ssl_protocol = sslproto.SSLProtocol( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 295, in __init__ sslcontext = _create_transport_context( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 55, in _create_transport_context sslcontext = ssl.create_default_context() File "/usr/local/lib/python3.12/ssl.py", line 713, in create_default_context context.load_default_certs(purpose)


Thank you

**Comment by simbaja** [comment]
I think that this has been resolved in 0.6.13, but let me know if not and I'll reopen.

**Comment by Waank1** [comment]
My bad, I updated the integration in HACS and it works now, Thanks!
