### ISSUE TITLE
Error Setting up entry

### ISSUE THREAD

**Issue by chansearrington** [simbaja/ha_gehome#30]
Also getting this

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174
Integration: GE Home (documentation)
First occurred: 7:22:18 AM (1 occurrences)
Last logged: 7:22:18 AM

Error setting up entry GE Home (joshewing02@hotmail.com) for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

_Originally posted by @joshewing02 in https://github.com/simbaja/ha_gehome/issues/29#issuecomment-894663365_

**Comment by chansearrington** [comment]
Started getting this when I updated to the current release this morning.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174 
Integration: GE Home (documentation) 
First occurred: 3:22:22 PM (1 occurrences) 
Last logged: 3:22:22 PM

Error setting up entry GE Home for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out

**Comment by simbaja** [comment]
Is there any error that occurs before this one?  You might need to search the logs a little bit.  All this is saying is that it timed out when trying to initialize.  That can be caused by many things such as network issues, credential issues, or an issue setting up a device (i.e. a bug).  The code is due for some refactoring, to be a bit more informative, but I haven't gotten there yet.

**Comment by opie546** [comment]
I got the same exact error sequence - this is a new setup and I am running v0.4.1

there is no other error that happens before these for me, they are at the top of the log file...

after that error, this one happens every minute:
`
2021-08-10 08:30:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry GE Home (EMAIL) for ge_home
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
await self.initialization_future
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
await self.initialization_future
File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
self._do_exit(exc_type)
File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
if not await coordinator.async_setup():
File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out
`

**Comment by simbaja** [comment]
Any chance that one of you can change the debug level in HA?  I'm not sure why it's not triggering the initialization complete, perhaps setting to debug might illuminate things a bit?

This is where the debug level can be set: https://www.home-assistant.io/integrations/logger/

**Comment by opie546** [comment]
log is attached - it looks like the problems start when it finds an unrecognized appliance - ErdUnitType is 6, which is my gas dryer

[ge_home_log_level_debug_startup.txt](https://github.com/simbaja/ha_gehome/files/6963265/ge_home_log_level_debug_startup.txt)

**Comment by opie546** [comment]
thanks! and the latest dev version fixed it. unrelated to this bug, but how does someone go about debugging a custom component like this?

**Comment by simbaja** [comment]
It's a bit of a pain to debug custom components honestly.  Basically, I just write a lot of details to the logger to hopefully figure out where something is failing.  Not sure if there's an easier way to do it.  Most of the logic is really in the SDK, and that is much easier to debug because you can run it separately and attach a debugger.

**Comment by simbaja** [comment]
@joshewing02 and @chansearrington, does the latest dev version solve your issues too?

**Comment by joshewing02** [comment]
Have nto had a chance to dig into this yet.  Traveling for work but plan on this weekend addressing.  Thanks for the follow up.

________________________________

**Comment by derekcentrico** [comment]
To comment on this, my issue from #33 is resolved here.  Setup the repo without issue.

**Comment by chansearrington** [comment]
How do I switch to the dev branch?

I installed using hacs

**Comment by chansearrington** [comment]
> @joshewing02 and @chansearrington, does the latest dev version solve your issues too?

@simbaja how do I switch to the dev branch?

I installed this via Hacs

**Comment by simbaja** [comment]
In hacs, if you show prereleases, those are based on the dev branch.  You
want 0.4.3-dev3.

**Comment by kksligh** [comment]
I hate to bring this back up, but I have the latest Dev version and it errors out no matter how many different ways I install. Any ideas? I can pull a log tomorrow

**Comment by simbaja** [comment]
> I hate to bring this back up, but I have the latest Dev version and it errors out no matter how many different ways I install. Any ideas? I can pull a log tomorrow

If you can post that log, we can hopefully figure it out.  Thanks for your help.

**Comment by kksligh** [comment]
Wow, false alarm...I went back to delete and reinstall to get the logs which I did about a dozen times earlier and now it's completely fine. You're that good! Thanks for this amazing integration!

**Comment by simbaja** [comment]
I'm assuming that it's working for everyone now, feel free to reopen if I am mistaken.  Thanks for all your help testing!
