### ISSUE TITLE
Can't setup ha_gehome anymore

### ISSUE THREAD

**Issue by mguaylam** [simbaja/ha_gehome#301]
I tried to update to the last version of ha_gehome (0.6.13) from (0.6.11) but I can't seem to setup it anymore.

I get this error :
```bash
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 232, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError(
ValueError: Config entry my@domain.com (01JC1N0AHDA7YQDBQ4VKDWD7BF) for ge_home.binary_sensor has already been setup!
```

I have Home Assistant with containers and my install method is manual.
I tried to wipe all entries from the .storage section but it still does it. I'm not sure what I'm missing.

**Comment by mguaylam** [comment]
I came back to  v0.6.11 and it works. Strange.

**Comment by NickStallman** [comment]
I can confirm that 0.6.13 broke for me as well and cannot log in. Downgrading to 0.6.12 works perfectly again.

**Comment by rsteckler** [comment]
Same - 6.13 breaks and downgrading to 6.12 fixes it.

**Comment by simbaja** [comment]
Seems to do with the new behavior related to the deprecated Home Assistant functionality, I've added some code for 0.6.14 that may help, let me know if it works after you try it.

**Comment by mguaylam** [comment]
I don't have the integration anymore because I'm using the [GEA adapter](https://github.com/geappliances/home-assistant-adapter) so I don't know if @NickStallman or @rsteckler could test and confirm if it work so I can close the issue. 🙂

**Comment by rsteckler** [comment]
Was on 6.12 and it worked.
Installed 6.13 and it broke as above.
Installed 6.14 and the integration loads, but has an error:
```
Failed setup, will retry: Could not connect to SmartHQ
```

I deleted the hub and tried to login to it again.  It failed with the same error.
Downgraded to 6.12 and it works again.

**Comment by NickStallman** [comment]
0.6.14 looks to be running happily for me. Thanks!
