### ISSUE TITLE
Error doing job: Task exception was never retrieved (None)

### ISSUE THREAD

**Issue by garyak** [simbaja/ha_gehome#304]
HA Core 2024.11.2 logs the following with version 0.6.13:

```
2024-11-16 02:51:19.938 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 334, in on_device_initial_update
    if self.connected and self.client.available:
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 59, in available
    return self._socket and not self._socket.closed
                                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?
```
Integration remains connected with values reported.

**Comment by VlastiBroucek** [comment]
https://github.com/simbaja/ha_gehome/issues/306#issue-2666606585

**Comment by AlternetConcept** [comment]
Same issue

Log details (ERROR)
Logger: gehomesdk.clients.base_client
Source: /usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py:141
First occurred: 5:42:29 PM (1 occurrences)
Last logged: 5:42:29 PM

'ClientConnection' object has no attribute 'closed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client
    await self._async_run_client()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 133, in _async_run_client
    await self._disconnect()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 246, in _disconnect
    if self._socket and not self._socket.closed:
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?
