### ISSUE TITLE
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?

### ISSUE THREAD

**Issue by livlif2dfullest** [simbaja/ha_gehome#316]
This is for a washer and dryer, using ge_home integration 0.6.13.  There's a new version of gehomesdk 0.5.30, the gehome integration I'm using says 0.5.29, unfortunately the changelogs are not shown for [gehomesdk ](https://pypi.org/project/gehomesdk/) so I cannot tell if this issue was fixed or not within it.
I see the following error in my Home Assistant log everyday:
```
2024-12-07 09:38:25.093 ERROR (MainThread) [gehomesdk.clients.base_client] 'ClientConnection' object has no attribute 'closed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 119, in _async_run_client
    async for message in CancellableAsyncIterator(socket, self._disconnect_requested):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/async_helpers.py", line 17, in CancellableAsyncIterator
    await pending_task
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 242, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/connection.py", line 294, in recv
    return await self.recv_messages.get(decode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/messages.py", line 150, in get
    frame = await self.frames.get(not self.closed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/messages.py", line 51, in get
    await self.get_waiter
asyncio.exceptions.CancelledError: Final process shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client
    await self._async_run_client()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 133, in _async_run_client
    await self._disconnect()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 246, in _disconnect
    if self._socket and not self._socket.closed:
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?
```

**Comment by simbaja** [comment]
Update to the latest version and it should be resolved.
