### ISSUE TITLE
Write HA State Issues

### ISSUE THREAD

**Issue by simbaja** [simbaja/ha_gehome#32]
Did a full deletion of the integration + entities.  Re-did the integration.

Serials seem different:

![image](https://user-images.githubusercontent.com/35814432/128642371-7fdca694-54cb-4646-99ec-85453c5aa00f.png)

Things seem to be working now!

Only remaining errors are:

```
2021-08-08 13:43:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 266, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 457, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity DS100880G Laundry Delay Time Remaining: >

2021-08-08 13:43:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 266, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 457, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity DS100880G Laundry Machine State: Off>

2021-08-08 13:43:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 266, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 457, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity SR371810N Laundry Delay Time Remaining: >

2021-08-08 13:43:32 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ge_home/update_coordinator.py", line 266, in on_device_update
entity.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 457, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity SR371810N Laundry Delay Time Remaining: >
```

So:
Dryer.Delay Time
Dryer.State
Washer.State

Unsure if they're worth investigating in a different issue, because this one seems to be ready to close!

_Originally posted by @steveredden in https://github.com/simbaja/ha_gehome/issues/28#issuecomment-894839020_

**Comment by simbaja** [comment]
Are there any errors before these start occuring?  Usually, I've seen an issue at startup that eventually results in this happening.

**Comment by steveredden** [comment]
Deleted the integration; full wipe of entities/devices; restarted core; reinstalled integration (no errors); reloaded integration (no errors).

Think we can just chalk it up to lingering duplicate devices, etc.
