### ISSUE TITLE
Oven shows as unavailable after being added and working for a bit

### ISSUE THREAD

**Issue by brijam** [simbaja/ha_gehome#322]
Great integration by the way, thank you so much.  I've been using this integration for over a year, and it has been flawless but since about September after making updates to HA or this integration my GE oven started showing up as unavailable.  Deleting and adding the oven as a device usually works, but this time it's really not sticking.

The logbook shows ordinary ordinary events and then everything going unavailable.

**Comment by brijam** [comment]
Edited to add that reloading the integration made the oven reappear this time.

**Comment by TiddlyWiddly** [comment]
This is happening to me as well. Entities go unavailable (that have been working for years) and a reload brings them back for a bit.

**Comment by simbaja** [comment]
Are there any errors in the log?

**Comment by TiddlyWiddly** [comment]
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/0c4bf79c-67c9-41df-aab1-984ce227f08c" />

`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:608
integration: Sensor (documentation, issues)
First occurred: December 14, 2024 at 4:17:57 PM (2208 occurrences)
Last logged: 11:02:07 AM

Error adding entity None for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    entity.add_to_platform_start(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.hass,
        ^^^^^^^^^^
        self,
        ^^^^^
        self._get_parallel_updates_semaphore(hasattr(entity, "update")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 231, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1352, in add_to_platform_start
    raise HomeAssistantError(
    ...<2 lines>...
    )
homeassistant.exceptions.HomeAssistantError: Entity 'None' cannot be added a second time to an entity platform`

**Comment by brijam** [comment]
Regrettably I had two power outages last night so my logs were wiped on reboot. If it happens again I will post the relevant logs.
