### ISSUE TITLE
Oven Integration Works Properly Except for Oven "Water Heater" Entity

### ISSUE THREAD

**Issue by waxhell** [simbaja/ha_gehome#41]
I have a GE Induction Range that has a built in Oven that is compatible with SmartIQ. It definitely looks like one of the earlier devices that were put out with Smart capabilities.

Model: PHB920SJ3SS
Type: Oven
Firmware: 0.0.0.0

The following entities are populated properly (I have renamed the device/entities away from the serial number and to just "oven"):

sensor.oven_cook_mode
sensor.oven_cook_time_remaining
sensor.oven_kitchen_timer
binary_sensor.oven_remote_enabled
switch.oven_sabbath_mode
sensor.oven_user_temp_offset

The item that does not work properly is the following:
water_heater.oven

This is what shows up in the logs:

2021-09-01 00:22:30 ERROR (MainThread) [homeassistant.components.water_heater] Error adding entities for domain water_heater with platform ge_home
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 711, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 203, in state_attributes
self.current_temperature,
File "/config/custom_components/ge_home/entities/oven/ge_oven.py", line 83, in current_temperature
return self.get_erd_value("RAW_TEMPERATURE")
File "/config/custom_components/ge_home/entities/oven/ge_oven.py", line 174, in get_erd_value
return self.appliance.get_erd_value(erd_code)
File "/usr/local/lib/python3.9/site-packages/gehomesdk/ge_appliance.py", line 136, in get_erd_value
return self._property_cache[erd_code]
KeyError: <ErdCode.UPPER_OVEN_RAW_TEMPERATURE: '0x510d'>

**Comment by simbaja** [comment]
I think this one might be solved in the newest pre release versions.  Can you give that a shot and let me know?  You might need to uninstall/reinstall if using hacs to prevent duplication errors.

**Comment by waxhell** [comment]
The newest pre-release fixed this issue. Thanks!
