### ISSUE TITLE
Invalid authentication non EU region account

### ISSUE THREAD

**Issue by mh-daedalus** [simbaja/ha_gehome#65]
Recently started getting 'Invalid authentication' when attempting to login for the integration to be created in HA.

Looking at the latest SmartHQ android application (v1.0.0.101.17) there is a link for Non-European accounts to sign in which resolves this problem of getting the authorization code.

Any chance we can get the alternative region added to login and have a user selection for each method?

```
Logger: gehomesdk.clients.async_login_flows
Source: /usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py:66

There was a problem getting the authorization code, response details: {'method': 'POST', 'cookies': <SimpleCookie: abgea_region='eu-west-1'>, '_real_url': URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate'), '_url': URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate'), '_body':..........etc.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 60, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
  File "/usr/local/lib/python3.9/site-packages/gehomesdk/clients/async_login_flows.py", line 95, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid credentials
```

Have been using it with Fisher Paykel Washing Machine WH1160F2.

Component has worked flawlessly until this recent update.

**Comment by rszemplinski** [comment]
Experiencing this in US region now

**Comment by simbaja** [comment]
Sorry, been dealing with Covid and catching up with work.  I see the new link in the page, let me see what I can do to figure something out.  Probably won't have time until this weekend though.

**Comment by rszemplinski** [comment]
No problem! Take your time, rest up and feel better

**Comment by jtbnz** [comment]
It is working again now for me. Authentication sucessful

**Comment by rszemplinski** [comment]
Unfortunately still ain't working for me

**Comment by simbaja** [comment]
Apologies for the delay, starting to feel better and catching up on things.  I'm hoping that one of you that has been having issues can go to the https://github.com/simbaja/gehome repository and run the websocket_example.py script (after setting up the credentials to use the correct region) and can attach a log/verify that it's accepting your login.

Once it's verified that the login works in the underlying library, I can work on incorporating it into the HA integration.

**Comment by mh-daedalus** [comment]
Thanks for the update @simbaja , apologies that I couldn't test the repository update sooner. Can confirm that switching from EU to US works in establishing a connection. Look forward to having it implemented into the HASS component.

```

root@test:~/gehome/examples# python3 websocket_example.py
2022-02-21 02:41:15,759 DEBUG    Using selector: EpollSelector
/root/gehome/examples/websocket_example.py:74: DeprecationWarning: The object should be created within an async function
  session = aiohttp.ClientSession()
2022-02-21 02:41:15,759 DEBUG    Getting OAuth2 token
2022-02-21 02:41:15,761 DEBUG    Client changed state: GeClientState.INITIALIZING to GeClientState.AUTHORIZING_OAUTH
2022-02-21 02:41:19,014 DEBUG    Getting WS credentials
2022-02-21 02:41:19,014 DEBUG    Client changed state: GeClientState.AUTHORIZING_OAUTH to GeClientState.AUTHORIZING_CLIENT
2022-02-21 02:41:19,551 INFO     Starting GE Appliances client
2022-02-21 02:41:19,560 DEBUG    Client changed state: GeClientState.AUTHORIZING_CLIENT to GeClientState.CONNECTING
2022-02-21 02:41:19,765 DEBUG    = connection is CONNECTING
2022-02-21 02:41:20,132 DEBUG    > GET /?access_token=TOKEN HTTP/1.1
2022-02-21 02:41:20,132 DEBUG    > Host: ws-us-west-2.brillion.geappliances.com
2022-02-21 02:41:20,132 DEBUG    > Upgrade: websocket
2022-02-21 02:41:20,132 DEBUG    > Connection: Upgrade
2022-02-21 02:41:20,132 DEBUG    > Sec-WebSocket-Key: KEY
2022-02-21 02:41:20,133 DEBUG    > Sec-WebSocket-Version: 13
2022-02-21 02:41:20,133 DEBUG    > User-Agent: Python/3.9 websockets/10.1
2022-02-21 02:41:20,569 DEBUG    < HTTP/1.1 101 Switching Protocols
2022-02-21 02:41:20,569 DEBUG    < Date: Mon, 21 Feb 2022 02:41:20 GMT
2022-02-21 02:41:20,569 DEBUG    < Connection: upgrade
2022-02-21 02:41:20,569 DEBUG    < upgrade: websocket
2022-02-21 02:41:20,569 DEBUG    < sec-websocket-accept: KEY
2022-02-21 02:41:20,570 DEBUG    = connection is OPEN
2022-02-21 02:41:20,570 DEBUG    > TEXT '{"kind": "websocket#subscribe", "action": "subs...["/appliance/*/erd/*"]}' [91 bytes]
2022-02-21 02:41:20,570 DEBUG    > TEXT '{"kind": "websocket#api", "action": "api", "hos...id": "List-appliances"}' [150 bytes]
2022-02-21 02:41:20,570 DEBUG    Client changed state: GeClientState.CONNECTING to GeClientState.CONNECTED
2022-02-21 02:41:20,781 DEBUG    < TEXT '{"kind":"websocket#connect","success":true}' [43 bytes]
2022-02-21 02:41:20,786 DEBUG    < TEXT '{"kind":"websocket#subscribe","success":true}' [45 bytes]
2022-02-21 02:41:21,013 DEBUG    < TEXT '{"kind":"websocket#api","id":"List-appliances",...2-18T16:58:20.746Z"}]}}' [439 bytes]
2022-02-21 02:41:21,013 DEBUG    DEVICEID marked available
2022-02-21 02:41:21,013 DEBUG    Adding appliance DEVICEID
2022-02-21 02:41:21,013 DEBUG    Requesting update for client DEVICEID
2022-02-21 02:41:21,014 DEBUG    > TEXT '{"kind": "websocket#api", "action": "api", "hos... "DEVICEID-allErd"}' [171 bytes]
2022-02-21 02:41:21,014 DEBUG    Registering update callback for GeAppliance(DEVICEID) (Unknown Type)
2022-02-21 02:41:21,014 DEBUG    Requesting features for client DEVICEID
2022-02-21 02:41:21,014 DEBUG    > TEXT '{"kind": "websocket#api", "action": "api", "hos...d": "Request-features"}' [172 bytes]
2022-02-21 02:41:21,136 DEBUG    < TEXT '{"resource":"/appliance/*/erd/*","kind":"websoc...:true,"change":"ADDED"}' [97 bytes]
2022-02-21 02:41:21,297 DEBUG    < TEXT '{"kind":"websocket#api","id":"DEVICEID-allE...2-18T17:00:22.345Z"}]}}' [1871 bytes]
2022-02-21 02:41:21,298 DEBUG    Setting ErdCode.MODEL_NUMBER to WH1160F2AA
2022-02-21 02:41:21,298 DEBUG    Setting ErdCode.SERIAL_NUMBER to 
2022-02-21 02:41:21,298 DEBUG    Setting ErdCode.APPLIANCE_TYPE to ErdApplianceType.WASHER
2022-02-21 02:41:21,298 DEBUG    Setting ErdCode.UNIT_TYPE to ErdUnitType.UNKNOWN
2022-02-21 02:41:21,298 DEBUG    Setting ErdCode.UNKNOWN_0099 to b'\x04'
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.WIFI_MODULE_SW_VERSION to 0.1.11.50
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.WIFI_MODULE_SW_VERSION_AVAILABLE to 0.0.0.0
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.ACM_UPDATING to False
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.APPLIANCE_SW_VERSION to 1.0.2.146
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.APPLIANCE_SW_VERSION_AVAILABLE to 0.0.0.0
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.APPLIANCE_UPDATING to False
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.LAUNDRY_MACHINE_STATE to Run
2022-02-21 02:41:21,299 DEBUG    Setting ErdCode.LAUNDRY_SUB_CYCLE to ErdLaundrySubCycle.RINSE
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_END_OF_CYCLE to False
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_TIME_REMAINING to 0:23:00
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_CYCLE to ErdLaundryCycle.INVALID
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_DELAY_TIME_REMAINING to 0:00:00
2022-02-21 02:41:21,300 DEBUG    Setting 0x2020 to b'\x00'
2022-02-21 02:41:21,300 DEBUG    Setting 0x2021 to b'&\x0f\x07\'(!)*+"'
2022-02-21 02:41:21,300 DEBUG    Got timespan value of 65535. Treating as None.
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_REMOTE_STATUS to False
2022-02-21 02:41:21,300 DEBUG    Setting ErdCode.LAUNDRY_REMOTE_POWER_CONTROL to ErdOnOff.NA
2022-02-21 02:41:21,300 DEBUG    Got initial appliance type for GeAppliance(DEVICEID) (ErdApplianceType.WASHER)
2022-02-21 02:41:21,300 DEBUG    Appliance state change detected in GeAppliance(DEVICEID) (ErdApplianceType.WASHER). Updated keys: ErdCode.MODEL_NUMBER, ErdCode.SERIAL_NUMBER, ErdCode.APPLIANCE_TYPE, ErdCode.UNIT_TYPE, ErdCode.UNKNOWN_0099, ErdCode.WIFI_MODULE_SW_VERSION, ErdCode.WIFI_MODULE_SW_VERSION_AVAILABLE, ErdCode.ACM_UPDATING, ErdCode.APPLIANCE_SW_VERSION, ErdCode.APPLIANCE_SW_VERSION_AVAILABLE, ErdCode.APPLIANCE_UPDATING, ErdCode.LAUNDRY_MACHINE_STATE, ErdCode.LAUNDRY_SUB_CYCLE, ErdCode.LAUNDRY_END_OF_CYCLE, ErdCode.LAUNDRY_TIME_REMAINING, ErdCode.LAUNDRY_CYCLE, ErdCode.LAUNDRY_DELAY_TIME_REMAINING, 0x2020, 0x2021, ErdCode.LAUNDRY_REMOTE_STATUS, ErdCode.LAUNDRY_REMOTE_POWER_CONTROL
2022-02-21 02:41:21,301 DEBUG    Appliance state change detected in GeAppliance(DEVICEID) (ErdApplianceType.WASHER)
2022-02-21 02:41:21,348 DEBUG    < TEXT '{"kind":"websocket#api","id":"Request-features"...705068","features":[]}}' [299 bytes]
2022-02-21 02:41:21,348 DEBUG    Received features [] for DEVICEID

```

**Comment by simbaja** [comment]
Excellent.  I've actually incorporated the update into the dev branch, feel free to try it out while I collect a few more updates.  I didn't publish as a release yet, but you can pull it manually instead of through HACS.

**Comment by veilofsecurity** [comment]
> Excellent.  I've actually incorporated the update into the dev branch, feel free to try it out while I collect a few more updates.  I didn't publish as a release yet, but you can pull it manually instead of through HACS.

Any update when this will get pushed and available via HACS?

**Comment by nahun** [comment]
For what its worth, I took the dev branch and installed the component in the `/config/custom_components` folder on my HAOS install and was now able to authenticate using the US region. So seems like it is good to go.

**Comment by simbaja** [comment]
I'm working to fix the support for microwaves (which is pretty broken I think), but will push this update to a HACS accessible branch afterwards.

**Comment by georgiosdelimpasis** [comment]
Hello, I am getting this error
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid credentials
with EU Account
