### ISSUE TITLE
v6.0 lost water filter life remaining sensor state for HA

### ISSUE THREAD

**Issue by rgabrielson11** [simbaja/ha_gehome#76]
Filter life remaining no longer is working.  Here are  logs

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 267, in on_device_update
    _LOGGER.debug(f"Updating {entity} ({entity.unique_id}, {entity.entity_id})")
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 524, in __repr__
    return super().__repr__()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in __repr__
    return f"<Entity {self.name}: {self.state}>"
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 410, in state
    value = self.native_value
  File "/config/custom_components/ge_home/entities/common/ge_erd_sensor.py", line 46, in native_value
    return self._convert_numeric_value_from_device(value)
  File "/config/custom_components/ge_home/entities/common/ge_erd_sensor.py", line 85, in _convert_numeric_value_from_device
    return int(round(value))
TypeError: type ErdWaterFilterLifeRemaining doesn't define __round__ method

**Comment by simbaja** [comment]
Give 0.6.1 a shot, should fix the issue

**Comment by rgabrielson11** [comment]
That worked. Had to remove and reinstall the device and restart a couple times. Can be closed.
